version: '3.7'
services:
  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
